### ISSUE TITLE
invalidPEMDocument when trying to create a ES256 Public/Private key

### ISSUE THREAD

**Issue by robertgmelo** [vapor/jwt-kit#204]
### Describe the issue

Using latest version of JWTKit, when I try to create a public or private key, I got `invalidPEMDocument` error.

`CryptoKitASN1Error error 7 ` 

### Vapor version

4.105.0

### Operating system and version

macOS Sequoia (15.x)

### Swift version

Swift 6.0.0-dev

### Steps to reproduce

``` 
let ecdsaPublicKey = "-----BEGIN PUBLIC KEY----- \(publicKey) -----END PUBLIC KEY-----"
let publicKey = try ES256PublicKey(pem: ecdsaPublicKey)
``` 
or 
```
let ecdsaPrivateKey = "-----BEGIN PRIVATE KEY----- \(privateKey) -----END PRIVATE KEY-----"
let privateKey = try ES256PrivateKey(pem: ecdsaPrivateKey)
```

Note: I've also tried with `Multiline String Literals` when creating `ecdsaPublicKey/ecdsaPrivateKey` , but got the same error.

**Comment by ptoffy** [comment]
Could you show your public key?

**Comment by robertgmelo** [comment]
```
-----BEGIN PUBLIC KEY----- MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERPCtlHWQk/a0IpM3wDl2LsZvpLlcicUMDmIxMsa8csu4XWUb3cIb6nu1e2zNmJ93w2n0HAe0LZw2RtpBIQC2YA== -----END PUBLIC KEY-----
```

**Comment by ptoffy** [comment]
@robertgmelo I'm guessing the `publicKey` variable doesn't contain the boundaries too otherwise they would be doubled. That said, the problem is likely that there are no newlines in your key. In a key's PEM format newlines are important, you can see how PEM keys are used in JWTKit's tests https://github.com/vapor/jwt-kit/blob/main/Tests/JWTKitTests/ECDSATests.swift#L340. You should try adding newlines after the first boundary and after every 64 characters in the key data, then try using them again.
What I'd recommend in the long run is base64url encoding the whole key (with boundaries) and using that (in an env var if it's the private key)

**Comment by robertgmelo** [comment]
Yup, I'm aware of that. As mentioned in the issue, I've tried with multiline string literals, which includes the new line, but I still get same error.

**Comment by robertgmelo** [comment]
The examples you provided are exactly how I was building the string originally:
```
let ecdsaPublicKey = """
-----BEGIN PUBLIC KEY-----
\(publicKey)
-----END PUBLIC KEY-----
"""

let ecdsaPrivateKey = """
-----BEGIN PRIVATE KEY-----
\(privateKey)
-----END PRIVATE KEY-----
"""
```

**Comment by robertgmelo** [comment]
One important to thing to mention is that on `4.x.x`, the value was the same, which means the key was correct, right? 

After updating the code to be compliant with v5 (replacing `JWTSigners` with `JWTCollection`), then we start seeing this.

**Comment by ptoffy** [comment]
As I said before you should not only add spaces after the initial boundary but also in the key data itself, every 64 characters. This means that this **won't** work

```swift
let ecdsaPublicKey = """
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERPCtlHWQk/a0IpM3wDl2LsZvpLlcicUMDmIxMsa8csu4XWUb3cIb6nu1e2zNmJ93w2n0HAe0LZw2RtpBIQC2YA==
    -----END PUBLIC KEY-----
    """
```

but this will
```swift
let ecdsaPublicKey = """
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERPCtlHWQk/a0IpM3wDl2LsZvpLlc
    icUMDmIxMsa8csu4XWUb3cIb6nu1e2zNmJ93w2n0HAe0LZw2RtpBIQC2YA==
    -----END PUBLIC KEY-----
    """
```

**Comment by robertgmelo** [comment]
Thanks for the details, @ptoffy. In that case, please feel free to close the issue. 

Hopefully other people do not face this, because it seems a drawback compatibility from v4 to v5.

**Comment by robertgmelo** [comment]
@ptoffy last question: I was wondering if it would be a good idea to include to the library the capability of adding newlines to the `pem` content.

What are your thoughts? 

I'd be glad to try to help on that.

**Comment by ptoffy** [comment]
I get where you're coming from but PEM files should be used as provided and not be touched by the library. Newlines are part of the spec and I'm afraid it's out of the library's scope to have to deal with PEM files for anything besides reading them. If removing newlines worked in v4 it was just because BoringSSL (which we swapped for SwiftCrypto) allowed so; requiring newlines is conformant to the spec and a lot of other libraries do so
